yihong0618/tg_bot_collections

hy_tg.py

- Use command in favor of regex
- Use subclass instead of monkeypatching

feat: use subclass instead of monkeypatch

---

hy_tg.py

fix: use spooled temp file to reduce memory usage

---

handlers/gemini.py

fix: delete reply after done

---

README.md
handlers/__init__.py
tg.py

Specify a command to disable. Can be used multiple times.

feat: add `--disable-command` option

---

README.md
setup.sh

做了一个安装python 环境和方便启动的shell脚本
功能包括 安装python 环境 创建虚拟环境 和 systemd 服务启动脚本
以后就可以用
systemctl start tgbotgemini.service 启动了
systemctl stop tgbotgemini.service 停止

feat: Add systemd service installation script to init project 

---

.env.example
README.md
setup.sh

This PR based on 
https://github.com/yihong0618/tg_bot_collections/pull/8
https://github.com/yihong0618/tg_bot_collections/pull/9
1 Separate the configuration files into .env 
Check readme to how to install 
安装时复制..env.example to .env   并修改.env 里面的2个配置变量即可
- Google_Gemini_API_Key (Google Gemini API KEY)
- Telegram_Bot_Token (Telegram Bot Token)
2  add sudo command if user is not root user. 
根据 用户是否为root 增加 sudo 前置命令
3 Service name now is tgbotyh.service  
服务名称改为 tgbotyh.service  
4 Remove empty line
删除多余空行

feat: Separate the configuration files into env

---

handlers/__init__.py
handlers/claude.py
handlers/gemini.py
handlers/yi.py
requirements.txt

Because I only have Gemini, so only tested with it.
While I have made the changes for Claude and Yi, it should work as well. :)
For Claude_pro, because of the stream mode, I keep the old way right now.

Split to multiple reply if text length is more than 4000 bytes

---

handlers/yi.py

typo fixed: you -> your in line 41

---

handlers/claude.py
handlers/gemini.py
handlers/yi.py

if the message starts with "new ", clear the player's history and start a new chat

feat: if the message starts with "new ", start a new chat directly

---

README.md
handlers/dify.py

I did it with manually set up such as `.env` file, and `pip install dify-client`
Code are formated with `black .`
Feel free to edit anything.
---
Kindly try my own bot https://t.me/tealmoon_ai_v1_bot
This is build by a modified version at [tg_bot_collections_lite](https://github.com/alterxyz/TealMoon_AI/tree/main/tg_bot_collections_lite),
This bot is hosted in an experimental environment, so it may be unstable or unresponsive at times.

feat: dify chatbot

---

.gitignore
README.md
handlers/__init__.py
handlers/cohere.py
handlers/useful.py

Kindly try my own bot https://t.me/tealmoon_ai_v1_bot
- Integrate Cohere's proactive and native web search capability
- Output the entire LLM message with its source link on Telegraph
- Add README file with tutorials on obtaining Cohere and Telegraph API keys
The new feature need:
```
pip install beautifulsoup4 # for html to Telegraph foramte
pip install Markdown # for markdown to html
pip install cohere # Cohere
```
The requirements.txt and env variables are not set up yet.

feat: Cohere Telegraph

---

handlers/__init__.py
handlers/cohere.py
handlers/useful.py

- fix: cohere long answer and garbled code
- fix: update same message
- refactor: Modulated
- chore: Switch on the top as "Customization"
- chore: Prompt for tasks
- feat: Support more LLM as optional
- feat: Summarization for final answer
- feat: Asynchronous/Thread for faster speed
- feat: Background Run some LLM, no telegram display, append to telegra.ph instead

Answer_it refine

---

handlers/__init__.py

the attributes of the tag `<a>` should be `attrs`.

Fixed issue with <a> tags not working in Telegraph.

---

handlers/gemini.py
handlers/useful.py

Fix stream message overtime
Fix gemini history.clear while stream
Feat: Complete mode (non stream)
Chore: preset some settings

Fix answer_it

---

handlers/__init__.py
handlers/useful.py

- gemini stream direct, other still thread run.
- gemini thread run disabled.
- formatting (black)

Fix answer_it gemini convo

---

handlers/__init__.py
handlers/useful.py

Enhance answer_it_handler to process image and replied messages
- Image message processing now supports Gemini, GPT, and Claude.

Enhance answer_it_handler to process image and replied messages

---

handlers/__init__.py
handlers/useful.py

Fixing hanging issue by:
- Prompt Gemini answer
- Display and submit backgrounded APPENDS first
- Then stream answers run
Telegraph for this demo: <https://telegra.ph/Answer-it-07-15-37>
Try at <https://t.me/tealmoon_ai_v1_alt_bot>

chore: ph/appends run first within threadpool

---

handlers/useful.py

Switched to path and use local full_answers

fix: get_page may return none

---

handlers/tweet.py

- reply with modified tweet link
- edit tweet link only message
- bot repeat modified link
- then delete original user message
Usage:  `/t <twitter/x link>`

 feat: FxTwitter handler

---

config.py
setup.sh

fix: ignore extra envs in env file

---

handlers/summary/__init__.py
handlers/summary/messages.py

fix: support search with space

---

handlers/summary/__init__.py
handlers/summary/messages.py
pyproject.toml

I have only tested the SQL part.
Hope other parts also work. :pray:

feat: get user stats in the group
